services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
      - "20000-20005:20000-20005"
    volumes:
      - ./data:/opt/asterixdb/datasets
